# Generated by Django 5.1.1 on 2025-01-16 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_friend_requests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friend_requests",
        ),
        migrations.AddField(
            model_name="user",
            name="sent_friend_requests",
            field=models.ManyToManyField(
                blank=True,
                related_name="received_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
